[project]
name = "bubble-sort"
version = "0.1.0"
description = "The bubble-sort package"
license = "MIT"

[remote]
author = "[AUTHOR]" # Add your Aleo Package Manager username, team's name, or organization's name.
